defencedigital/moduk-frontend-guidance-site

- dprint.json
- package.json
This makes the same updates to the lint-staged and dprint configurations as in https://github.com/defencedigital/moduk-frontend/pull/134.
> Update lint-staged and dprint configs

- dprint.json
It doesn't know that they are mixed Nunjucks and Markdown files, so it ends up misformatting them.
> chore(dprint): Exclude Eleventy .md files from formatting

- .stylelintrc.json
- package-lock.json
- package.json
This: 
- ignores Eleventy .md files in lint-staged for the same reason as in #20 
- adds some Prettier exceptions to stylelint to stop them conflicting with each other
- makes lint-staged run stylelint
> chore: Update lint-staged and stylelint config

- src/site/_includes/layouts/_base.njk
- src/site/components/preview/index.njk
Think this accidentally crept into the page when opening an example in a new window.
> fix(example-window): Remove footer background

- .github/workflows/lint-and-test.yml
- .github/workflows/release.yml
- .release-it.js
- package-lock.json
- package.json
This adds a GitHub Actions workflow to automatically create a GitHub release when a PR is merged to main.
This is a simplified version of the workflow in https://github.com/defencedigital/moduk-frontend. Publishing to npm is not required here. It also does not bother updating the version `package.json` as the package isn't being published. (The version in package.json has been changed to make this clear.)
As previously, the approach was tested in https://github.com/jpveooys/github-actions-testing-v2 as much as possible.
> ci: Add workflow to create GitHub releases on merge

- .release-it.js
This resolves a problem where a release would fail if two PRs were merged in quick succession.
The failure was due to `git push --follow-tags` failing on the release build for the first PR due it the commit being behind the latest `main`.
This instead makes release-it push only the relevant tag. It was tested in https://github.com/jpveooys/github-actions-testing-v2.
> ci: Fix error pushing tag during release

- Dockerfile
- nginx/misc-http-section.conf
This configures nginx to use relative redirects instead of absolute ones, which sidesteps problems about knowing the correct protocol and port to redirect to (which nginx won't necessarily know).
I didn't go for `port_in_redirect off;` as:
- it would break redirects locally
- it wouldn't fix nginx redirecting to `http://` instead of `https://` in D2S
> fix(nginx): Use relative redirects

- .github/workflows/lint-and-test.yml
This updates both the end-to-end and visual regression tests to use two shards on GitHub Actions, as they're now taking a few minutes.
Rough comparison of before and after:
> ci: Shard Playwright tests

- Dockerfile
This makes a simple change to the Dockerfile to not download Playwright browsers when `npm ci` is run, as an easy way to speed up building the container image.
> build(container): Don't download Playwright browsers

- Dockerfile
- nginx/assets-server-section.conf
- nginx/common-server-section.conf
- nginx/owasp-server-section.conf
This PR adds cache control for 1 hour only to deal with iframe issues. 
I have not made it longer because we have no versioning on the js files yet. e.g `main.3edfsd.js`  
I have also left out the `immutable`  directive for the same reason. 
```
Cache-Control: max-age=3600, public
```
To test I built the image locally and 
`podman build -f Dockerfile -t moduk-guidance`
run the container
`podman run --rm -e IS_PROD=true -d -p 8080:8080 localhost/moduk-guidance:latest`
> fix: Add cache control for static files

- e2e/tests/component-preview.spec.ts
- src/site/_includes/components/component-preview/index.scss
This adds a minimum width and height to component examples, which restricts how small they can be resized.
> feat(component-preview): Add minimum size when resizing example

- package-lock.json
This updates Webpack to resovle an alert flagged by `npm audit`.
> deps-dev: Update Webpack to version 5.61.1

- Dockerfile
This makes a few small tweaks to the Dockerfile so that `npm ci` is only rerun if `package.json` or `package-lock.json` has changed.
> build(container): Avoid reinstalling npm packages when files change

- docs/CONTRIBUTING.md
This corrects the title of the contributing docs and adds a commit type that wasn't listed.
> docs(contributing): Correct title and update commit types

- e2e/tests/cookie-banner.spec.ts
- e2e/tests/cookie-settings.spec.ts
- package-lock.json
- package.json
This updates Playwright to the latest version. That includes removing some `@ts-expect-error`s that are no longer needed (and now causing linter errors).
> deps-dev: Update Playwright to version 1.32.3

- .eleventy.js
- e2e/tests/component-preview.spec.ts
- src/site/_includes/components/component-preview/macro.njk
This adds a React tab to examples for supported components containing a code snippet.
The code for the snippet is imported from the `@moduk/frontend` package and run through Prettier to reduce the line length.
If a matching React example is not found, the React tab is hidden.
Note: This shouldn't be merged this until the React components are actually ready for use.
> feat(examples): Add React code snippets

- .github/dependabot.yml
This enables grouped updates for a few of the main groups of dependencies that are normally updated together, in line with the updates made in https://github.com/defencedigital/moduk-frontend/pull/331.
> ci(dependabot): Add grouped updates

- scripts/run-playwright-container.sh
This updates `scripts/run-playwright-container.sh` so that an overlay file system is used when mounting the current directory (including node_modules). This means `node_modules` starts off the same as the host, but any changes written to it in the container are temporary and limited to the container itself.
The `e2e` directory is mounted normally so that reports and screenshots are written to the host.
This speeds up the `npm install` part of `npm run test:visual` for me (on Ubuntu).
@adamledwards Could you check if this works okay for you?
> test(visual-regression): Allow container volume args to be overridden

- .github/actions/merge-playwright-reports/action.yml
- .github/workflows/lint-and-test.yml
- .gitignore
- playwright.config.ts
This updates the GitHub Actions workflow to [merge the reports from each Playwright shard](https://playwright.dev/docs/test-sharding#merging-reports-from-multiple-shards), in line with https://github.com/defencedigital/moduk-frontend/pull/354.
> ci(e2e): Merge sharded Playwright reports

- src/site/_includes/layouts/_base.njk
The path to the mask icon for Safari was incorrect in the relevant `<link>` element.
> fix: Correct path to Safari mask icon

- src/site/_includes/components/navigation/index.scss
- src/site/_includes/components/phase-banner/index.scss
This adds some some additional borders to the primary navigation and phase banner that were missing when high contrast mode is active.
> fix: Improve high contrast mode

- package-lock.json
Bumps @babel/traverse to 7.23.2, get-func-name to 2.0.2, and postcss to 8.4.31
> deps-dev: Run `npm audit fix`

- .eleventy.js
- Dockerfile
`eleventy-plugin-rev` hardcodes the `md5` hashing algorithm, but this is not supported by OpenSSL3
> fix(build on d2s): Replace eleventy hashing algorithm

- .github/actions/prepare-environment/action.yml
- Dockerfile
The Dockerfile build was failing due to too many open files. Updating the base images to use UBI9 fixes this.
> build: Update base images to UBI9
